services:

  namenode:
    platform: linux/amd64
    image: apache/hadoop:3
    container_name: namenode
    hostname: namenode
    command: ["hdfs", "namenode"]
    ports:
      - "9870:9870"
      - "9000:9000"
    env_file:
      - ./hadoop.env
    volumes:
      - ./Students_Data:/Students_Data
    networks:
      - bigdata-net

  datanode:
    platform: linux/amd64
    image: apache/hadoop:3
    container_name: datanode
    hostname: datanode
    command: ["hdfs", "datanode"]
    depends_on:
      - namenode
    env_file:
      - ./hadoop.env
    volumes:
      - ./Students_Data:/Students_Data
    networks:
      - bigdata-net

  spark-master:
    platform: linux/amd64
    image: apache/spark:3.5.1-scala2.12-java11-python3-ubuntu
    container_name: spark-master
    hostname: spark-master
    command: >
      /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - SPARK_MASTER_HOST=spark-master
    volumes:
      - ./Students_Data:/Students_Data
    networks:
      - bigdata-net

  spark-worker:
    platform: linux/amd64
    image: apache/spark:3.5.1-scala2.12-java11-python3-ubuntu
    container_name: spark-worker
    hostname: spark-worker
    depends_on:
      - spark-master
    command: >
      /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    ports:
      - "8081:8081"
    environment:
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=2G
    volumes:
      - ./Students_Data:/Students_Data
    networks:
      - bigdata-net

  spark-client:
    platform: linux/amd64
    image: apache/spark:3.5.1-scala2.12-java11-python3-ubuntu
    container_name: spark-client
    hostname: spark-client
    stdin_open: true
    tty: true
    command: /bin/bash
    depends_on:
      - spark-master
    volumes:
      - ./Students_Data:/Students_Data
    networks:
      - bigdata-net

  hive-server:
    platform: linux/amd64
    image: apache/hive:4.0.0
    container_name: hive-server
    hostname: hive-server
    depends_on:
      - namenode
      - datanode
    ports:
      - "10000:10000"
      - "10002:10002"
    environment:
      - SERVICE_NAME=hiveserver2
    volumes:
      - ./Students_Data:/Students_Data
    networks:
      - bigdata-net

networks:
  bigdata-net:
    driver: bridge